apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci
  namespace: floci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci
  template:
    metadata:
      labels:
        app: floci
    spec:
      containers:
        - name: floci
          image: hectorvent/floci:latest
          ports:
            - containerPort: 4566
          env:
            - name: QUARKUS_HTTP_PORT
              value: "4566"
            - name: FLOCI_PORT
              value: "4566"
            - name: FLOCI_STORAGE_MODE
              value: "memory"
            - name: FLOCI_DEFAULT_REGION
              value: "us-east-1"
            - name: FLOCI_HOSTNAME
              value: "floci.floci.svc.cluster.local"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
