apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-dev-analytics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oss-slu/k8s-manifests
    targetRevision: HEAD
    path: oss-dev-analytics
  destination:
    server: https://kubernetes.default.svc
    namespace: oss-dev-analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
