apiVersion: v1
kind: PersistentVolume
metadata:
  name: oss-dev-analytics-data
  labels:
    app: oss-dev-analytics
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /srv/oss-slu/oss-dev-analytics/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oss03
