apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-data
  namespace: oss-dev-analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: oss-dev-analytics
