apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mdma-database
  namespace: mdma
spec:
  instances: 1

  storage:
    size: 5Gi
    storageClass: manual

  bootstrap:
    initdb:
      database: mdma
      owner: admin
      secret:
        name: mdma-db-secret

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      log_min_duration_statement: "1000"
