apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdma-database-1
  labels:
    app: mdma
    component: database
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /srv/oss-slu/mdma/database-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - oss03
